[project]
name = "django-starter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.3",
    "django-allauth>=65.2.0",
    "django-cleanup>=9.0.0",
    "django-htmx>=1.21.0",
    "pillow>=11.0.0",
]
